### ISSUE TITLE
Can knots.option="equally-spaced" be changed?

### ISSUE THREAD

**Issue by rdeneer** [lxiao5/face#1]
Can I change from equally-spaced knots to knots placed at the quantiles? It seems like all the code is in place in `select.knots` but the option is commented-out in the `face.sparse` arguments.

**Comment by cli9** [comment]
The short answer is yes. We tried that before as experimental options in numerical studies and it worked well. You may look into functions pspline.setting.R and pspline.R, the code is also in place. Need to comment out line 37 of pspline.R if you want to switch to "quantile".
